### PR TITLE
RHTAPBUGS-1151: ArgoCD Namespace

### PR DESCRIPTION
**Pull request by otaviof**
Using `rhtap` for ArgoCD's Namespace.

### CODE REVIEW

**Review by Roming22 — APPROVED** [review]
/lgtm

**Comment by flacatus** [comment]
Failed to load live state: Namespace "flavius-e2e-development" for Service "flavius-e2e" is not managed

i get this kind of errors

**Comment by yangcao77** [comment]
@flacatus  can you check your gitops repo under app-of-apps/application-dev.yaml to see if the label has been set to `rhtap`? for example: https://github.com/stephanie-cy/node-app2-gitops/blob/07c333b6d94f5a52b366f6009d97f3cb474e1314/app-of-apps/application-dev.yaml#L16-L19

**Comment by flacatus** [comment]
https://github.com/rhtap-hub/flavi-2-gitops/blob/main/app-of-apps/application-dev.yaml#L19

**Comment by flacatus** [comment]
I just realized that installer created my namespace manage-by with openshift-gitops instead of rhtap... I fixed that and i got :
```log
          message: 'namespaces "rhtap-integ-development" is forbidden: User "system:serviceaccount:rhtap:rhtap-argocd-argocd-application-controller" cannot patch resource "namespaces" in API group "" in the namespace "rhtap-integ-development"'
```

**Comment by yangcao77** [comment]
@flacatus From the error message, it looks like your SA does not have permission to patch namespaces.

**Comment by flacatus** [comment]
that error is comming from argocd

**Comment by flacatus** [comment]
Yes, that SA is created by installer

**Comment by flacatus** [comment]
Screenshot from 2024-03-12 10-02-54

**Comment by otaviof** [comment]
@jduimovich, please review this PR, thanks in advance!

**Review by yangcao77 — APPROVED** [review]
lgtm

**Pull request merged**
