### PR TITLE
Rename gitops component dir

### PR DESCRIPTION
**Pull request by yangcao77**
This PR rename component Dir from `http` to `${{ parameters.name }}`

example generated gitops repo: https://github.com/stephanie-cy/go-app5-gitops/tree/main/components/go-app5

### CODE REVIEW

**Review by jduimovich — COMMENTED** [review]
this is currently correct  argoComponent: `'./components/http/overlays/development'`
after the rename it would be 
 `'./components/${{ parameters.name }}/overlays/development'`
There is no kustomize currently in the ` './components/${{ parameters.name }}` folder  so this won't work 

Options, we add a kustomize that references the one environment (for now) but eventually I had been assuming there be a single folder ./application and it will reference each component  as they are added to an existing gitops repo (future) 
``` 
../components/component1
../components/component1
``` 

The other pattern is we do app of apps and `./application` is an app set or a bunch of apps which all reference `../component/application.yaml`

**Comment by yangcao77** [comment]
@jduimovich 
pushed a new commit to update the path to be `./components/${{ parameters.name }}/overlays/development`

I was checking the demo layout sample, the `application/` folder still need to point to `overlays/development` as well, unless we have a kustomization file to the root of each component, is that correct?
https://github.com/jduimovich/demo-layout/blob/main/argocd/application/kustomization.yaml

**Comment by jduimovich** [comment]
>  was checking the demo layout sample, the application/ folder still need to point to overlays/development as well, unless we have a kustomization file to the root of each component, is that correct?

Yes, when we actually create an application directory it will need a kustomize as you describe. 
As quick workaround since we have 1 component you see   we point the argocd application directly at the development overlay for the one component :) 

When we ./applications directory it will include a kustomize with ../component/c1, ../component/c2 etc
The application yaml will point to ./applications which then includes the c1.c2 etc components

**Review by jduimovich — APPROVED** [review]
LGTM now
We can generate, do an oc apply of the application and the app should run and PaC as well

**Pull request merged**
